# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: mvn -P prod clean install
      env: # Or as an environment variable
        MONGO_URI: ${{ secrets.MONGO_URI }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: Run Spring Boot application
      run:  ./mvnw -P prod spring-boot:run &
      env: # Or as an environment variable
        MONGO_URI: ${{ secrets.MONGO_URI }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: Let's wait for the application to be initialized
      run: while ! lsof -Pi :8080 -sTCP:LISTEN -t > /dev/null; do    sleep 5; done
    - name: Health check
      run: curl localhost:8080/actuator/health
