# This is a basic workflow to help you get started with Actions

name: sync

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Build with Maven
        run: mvn -P prod clean install
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Run Spring Boot application
        run:  ./mvnw -P prod spring-boot:run &
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Let's wait for the application to be initialized
        run: while ! lsof -Pi :8080 -sTCP:LISTEN -t > /dev/null; do    sleep 5; done
      - name: Health check
        run: curl localhost:8080/actuator/health
      - name: Sync activities
        run: curl -X POST localhost:8080/api/v1/sync/activities
